In [15]:
!pip install pandas

Requirement already satisfied: pandas in /home/phuchoang/Documents/ecommerce-ajax-servlet/.venv/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in /home/phuchoang/Documents/ecommerce-ajax-servlet/.venv/lib/python3.12/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/phuchoang/Documents/ecommerce-ajax-servlet/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/phuchoang/Documents/ecommerce-ajax-servlet/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [16]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="root123",
)
conn.cursor().execute("use ecommerce_new")

In [17]:
import pandas as pd
def execute_query(title, sql):
    print(f"🔍 {title}")
    try:
            # Sử dụng pandas để đọc và hiển thị cho đẹp
        df = pd.read_sql(sql, conn)
        if df.empty:
            print("Không tìm thấy kết quả phù hợp.")
        else:
            display(df) # Hàm display chuyên dùng cho Jupyter
        print("-" * 50)
    except Exception as e:
        print(f"❌ Lỗi: {e}")

In [18]:
execute_query("Select all users", "select * from users;")

🔍 Select all users

/tmp/ipykernel_9064/314929007.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql, conn)

,user_id,username,password,role,created_at,updated_at
0,1,admin_user,P@ssw0rd123,ADMIN,2026-03-12 07:50:32,2026-03-12 07:50:32
1,2,customer01,password123,USER,2026-03-12 07:50:32,2026-03-12 07:50:32
2,3,airflow,$2a$10$5sLPjgnkAmLi.IjOWRF97.7YyjZ5m./TwlIJMfE...,USER,2026-03-12 07:56:14,2026-03-12 07:56:14
3,4,airflow_2,$2a$10$JWXcTIj4L8jYhUaKrcDVeuEmut9mNr3j49QQpNf...,USER,2026-03-12 07:59:51,2026-03-12 07:59:51

--------------------------------------------------

In [19]:
execute_query("SELECT ALL PROFILES", "select * from profiles;")

🔍 SELECT ALL PROFILES

/tmp/ipykernel_9064/314929007.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql, conn)

,profile_id,user_id,full_name,phone,email,address
0,1,3,nguyen van a,0913123123,nguyenvana@example.com,hcmc

--------------------------------------------------